services:

  faq:
    container_name: "myaila-faq"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${DOCKER_FAQ_PORT:-3005}:3000"
    volumes:
      - ./docs:/app/docs
    restart: unless-stopped
